[font]
size = 10.0

[font.bold]
# family = "Comic Code Nerd Font"
# family = "Fira Code Nerd Font"
# family = "JetBrains Mono Nerd Font"
# family = "Roboto Mono Nerd Font"
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "Comic Code Nerd Font"
# family = "Fira Code Nerd Font"
# family = "JetBrains Mono Nerd Font"
# family = "Roboto Mono Nerd Font"
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "Comic Code Nerd Font"
# family = "Fira Code Nerd Font"
# family = "JetBrains Mono Nerd Font"
# family = "Roboto Mono Nerd Font"
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
# family = "Comic Code Nerd Font"
# family = "Fira Code Nerd Font"
# family = "JetBrains Mono Nerd Font"
# family = "Roboto Mono Nerd Font"
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1
