#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='lvim ~/.config/lvim/config.lua'

alias nvim='nvim' 

alias vf="fzf | xargs -r -I % $EDITOR %"

# get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"


# alias m="git checkout master"
# alias s="git checkout stable"

#mine 

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# these are from bashrc
alias ll='ls -lav --ignore=..'   # show long listing of all except ".."
alias l='ls -lav --ignore=.?*'   # show long listing but no hidden dotfiles except "."

alias sudo="doas"
alias ls='eza -al --color=always --icons --group-directories-first'
alias i3="i3lock -C -i /home/chris/.local/bin/arch-wallpaper.jpg"
alias nv="nvim"
alias snv="sudo nvim"
alias ka="killall"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -v"
alias ln="ln -i"
alias cl="clear"
alias v="vim"
alias wiki="nvim ~/emanotes/index.md"
alias gp="git add . && git commit -m 'autopush' && git push"
alias mkdir="mkdir -pv"
alias lf="lfub"
# alias kx="killall sxhkd && sxhkd &"
alias cat="bat -p"
alias merge="xrdb -merge ~/.Xresources"
# alias m="mailsync"
# alias se="du -a ~/.local/bin/* ~/.config/* | awk '{print $2}' | fzf | xargs -r nvim"



 


# cd navigation taken from dt gitlab bashrc
up () {
  local d=""
  local limit="$1"

  # Default to limit of 1
  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
    limit=1
  fi

  for ((i=1;i<=limit;i++)); do
    d="../$d"
  done

  # perform cd. Show error if cd fails
  if ! cd "$d"; then
    echo "Couldn't go up $limit dirs.";
  fi
}


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/chris/.local/share/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/chris/.local/share/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/chris/.local/share/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/chris/.local/share/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<






