#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export $EDITOR="nvim" 
# export PATH=$HOME/.cargo/bin:$PATH
# export PATH="$PATH:./node_modules/.bin"
 # eval "$(zoxide init zsh)"


# export visual="nvim"
# export browser="firefox"
# export movplay="mpv"
# export term=xterm-256color
#
# # ~/ Clean up:
# export LESSHISTFILE="-"
#
# #testing
#
# # export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
# export NOTMUCH_CONFIG=$XDG_CONFIG_HOME/notmuch/default/config
# export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
# export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
# export CARGO_HOME="$XDG_DATA_HOME/cargo"
# export URLVIEW_CONFIG="$XDG_CONFIG_HOME/urlview/config"
# export GOPATH="$XDG_DATA_HOME/go"
# export GIT_CONFIG="$XDG_CONFIG_HOME/git/config"
#
# #xdg ninja recommends
# export GNUPGHOME="$XDG_DATA_HOME/gnupg"
# export PASSWORD_STORE_DIR="$XDG_DATA_HOME/.password-store"
# alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"
# export HISTFILE="$XDG_DATA_HOME/zsh/history"
#
#
#
#
















# eval "`pip completion --zsh`"

#
# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<
#
