#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export TERM=xterm-256color
export EDITOR='nvim'
export VISUAL='nvim'
export TERMINAL='kitty'
export BROWSER='qutebrowser'
export MANPAGER='nvim +Man!'
export MANWIDTH=999


export BAT_THEME="Catppuccin Macchiato"
export FZF_DEFAULT_OPTS=" \
--color=bg+:#363A4F,bg:#24273A,spinner:#F4DBD6,hl:#ED8796 \
--color=fg:#CAD3F5,header:#ED8796,info:#C6A0F6,pointer:#F4DBD6 \
--color=marker:#B7BDF8,fg+:#CAD3F5,prompt:#C6A0F6,hl+:#ED8796 \
--color=selected-bg:#494D64 \
--color=border:#6E738D,label:#CAD3F5"

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"   
eval "$(fnm env --use-on-cd --shell zsh)"
eval "$(atuin init zsh)"
