# Catppuccin Macchiato Color Palette
set -l foreground cad3f5
set -l selection 363a4f
set -l comment 8087a2
set -l red ed8796
set -l orange f5a97f
set -l yellow eed49f
set -l green a6da95
set -l purple f0c6c6
set -l cyan 8aadf4
set -l pink f5bde6
set -l gray 6e738d
set -l user 8bd5ca
set -l host_remote a6da95
set -l host_local 8aadf4

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $cyan
set -g fish_color_keyword $red
set -g fish_color_quote $green
set -g fish_color_redirection $pink
set -g fish_color_end $orange
set -g fish_color_option $green
set -g fish_color_error $red
set -g fish_color_param $purple
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $pink
set -g fish_color_escape ee99a0
set -g fish_color_autosuggestion $gray
set -g fish_color_cancel $red
set -g fish_color_cwd $yellow
set -g fish_color_user $user
set -g fish_color_host $host_local
set -g fish_color_host_remote $host_remote
set -g fish_color_status ed8796

# Completion Pager Colors
set -g fish_pager_color_progress $gray
set -g fish_pager_color_prefix $pink
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $gray
