[tools]
bat = "latest"
lsd = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
node = "25"
neovim = "0.12.1"
starship = "latest"
tree-sitter = "0.26.1"
atuin = "latest"
yazi = "26.1.22"
eza = "latest"
