[tools]
bat = "latest"
lsd = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
node = "25"
neovim = "0.11.5"
starship = "latest"
tree-sitter = "0.25.10"
atuin = "latest"
yazi = "26.1.22"
eza = "latest"
