[tools]
bat = "latest"
ripgrep = "15.1.0"
fzf = "0.67"
fd = "latest"
neovim = "0.12.0"
starship = "1.24.2"
tree-sitter = "0.26.1"
atuin = "18.13.6"
yazi = "26.1.22"
eza = "latest"
jq = "latest"
zoxide = "0.9.8"
java = "17"
opencode = "latest"
node = "25.6.0"
hugo-extended = "0.147.7"
usage = "latest"
btop = "latest"

[settings]
trusted_config_paths = [
    '~/.local/share/repos',
]
color_theme = "catppuccin"
jobs = 8
