# Catppuccin Latte Color Palette
set -l foreground 4c4f69
set -l selection ccd0da
set -l comment 8c8fa1
set -l red d20f39
set -l orange fe640b
set -l yellow df8e1d
set -l green 40a02b
set -l purple ea76cb
set -l cyan 1e66f5
set -l pink ea76cb
set -l gray 9ca0b0
set -l user 179299
set -l host_remote 40a02b
set -l host_local 1e66f5

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $cyan
set -g fish_color_keyword $red
set -g fish_color_quote $green
set -g fish_color_redirection $pink
set -g fish_color_end $orange
set -g fish_color_option $green
set -g fish_color_error $red
set -g fish_color_param dd7878
set -g fish_color_comment $comment
set -g fish_color_selection --background=$selection
set -g fish_color_search_match --background=$selection
set -g fish_color_operator $pink
set -g fish_color_escape e64553
set -g fish_color_autosuggestion $gray
set -g fish_color_cancel $red
set -g fish_color_cwd $yellow
set -g fish_color_user $user
set -g fish_color_host $host_local
set -g fish_color_host_remote $host_remote
set -g fish_color_status $red

# Completion Pager Colors
set -g fish_pager_color_progress $gray
set -g fish_pager_color_prefix $pink
set -g fish_pager_color_completion $foreground
set -g fish_pager_color_description $gray
