# keybinds
set -g prefix C-Space
set -g prefix2 C-b
bind C-Space send-prefix

bind-key r run-shell " \
			tmux source-file ~/.config/tmux/tmux.conf > /dev/null; \
			tmux display-message 'Sourced tmux_config!'"

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

bind-key c kill-window
bind-key w new-window
bind-key x kill-pane
bind-key W choose-window
bind-key T clock-mode

# its funny -h is vertical split and -v is horizontal. Makes no sense.
bind v split-window -h -c "#{pane_current_path}"
bind H split-window -v -c "#{pane_current_path}"
bind k kill-pane -a                  # Kill all panes except for the current one

# CTRL+hjkl to switch panes (vim-style)
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Easier and faster switching between next/prev window
bind -n C-p previous-window
bind -n C-n next-window

bind-key -n M-y if-shell -F '#{==:#{session_name},popup}' \
  'detach-client' \
  'display-popup -E -d "#{pane_current_path}" -w 50% -h 50% "tmux new-session -A -s popup"'

# opts
set-option -g detach-on-destroy off
setw -q -g utf8 on
set -g mouse on
set -g renumber-windows on
set -g set-titles on
set -sg repeat-time 500
set -g default-terminal "tmux-256color"
# set-option -ga terminal-overrides ",foot:Tc"
set -ga terminal-overrides ",*:RGB"
set -s escape-time 0
set -g history-limit 50000
set -g display-time 4000
set -g status-interval 1
set -g focus-events on
setw -g aggressive-resize on
set -g base-index 1
setw -g pane-base-index 1
set -g visual-activity off
set -g set-clipboard on
set -g allow-passthrough on
# update so i can change wallpapers with imv when launched through yazi
set-option -g update-environment "WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_RUNTIME_DIR DISPLAY"


# Status bar
set -g status on
set -g status-justify centre
set -g status-position top
set -g status-interval 5
set -g status-left-length 90
set -g status-right-length 90
set -g status-style "bg=default"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#8aafd4"
set -g message-style "fg=#24273a,bg=#8aafd4"
set -g message-command-style "fg=#24273a,bg=#8aafd4"
set -g mode-style "bg=#8aafd4,fg=#24273a"
set -g window-status-separator ""
set -gw automatic-rename on
setw -g window-status-format "#[fg=brightblack,noitalics] #I:#W "
setw -g window-status-current-format "#[bg=#8aafd4,bold,noitalics] #[fg=#24273a] #I:#W "

set -g status-left "#[fg=#24273a,bg=#8aafd4,bold] #S #[fg=#24273a]  #[bg=green,bold]#{?pane_in_mode,COPY ,}#[bg=red,bold]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}"
# Right: hostname (omarchy style)
set -g status-right "#[fg=brightblack,bold]#h "
