require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
-- require "user.colorscheme"
require "user.impatient"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.catppuccin"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.colorizer"
require "user.vimwiki"
require "user.zen-mode"
require "user.twilight"
require "user.quickscope"
-- require "user.notify"
require "user.hop"
require "user.illuminate"
require "user.toggleterm"
--
-- require "user.disable"
-- require "user.tokyonight"
-- require "user.dracula"
 -- require "user.nord"

