abbr em "sudo emerge --ask"
abbr ew "sudo emerge-webrsync"
abbr ea  "sudo emaint -a sync"
abbr ems "sudo emerge --sync"
abbr emn "sudo emerge --ask --update --deep --newuse @world"
abbr emc "sudo emerge --ask --update --deep --changed-use @world"
abbr ema "sudo emerge --ask --autounmask"
abbr emu "sudo emerge --ask -uDU --keep-going --with-bdeps=y @world"
abbr emd "sudo emerge --ask --depclean"
abbr update-grub "sudo grub-mkconfig -o /boot/grub/grub.cfg"
abbr ke "cd /usr/src/linux/ && sudo make menuconfig"
abbr drivers "sudo emerge @module-rebuild"
abbr golang "sudo emerge @golang-rebuild"
# abbr mk "sudo /usr/src/linux/rebuild-kernel.sh"
