# vim: filetype=sh
abbr cac "cd /home/chris/.cache/; and ls -a"
abbr cf "cd /home/chris/.config/; and ls -a"
abbr D "cd /home/chris/dl; and ls -a"
abbr d "cd /home/chris/docs; and ls -a"
abbr dt "cd /home/chris/docs/tex/; and ls -a"
abbr ds "cd /home/chris/docs/ms/; and ls -a"
abbr dp "cd /home/chris/docs/sprops/; and ls -a"
abbr dw "cd /home/chris/docs/vimwiki/; and ls -a"
abbr dn "cd /home/chris/docs/vimwiki/notes/; and ls -a"
abbr dm "cd /home/chris/docs/rmd/; and ls -a"
abbr rr "cd /home/chris/.local/src; and ls -a"
abbr h "cd /home/chris; and ls -a"
abbr m "cd /home/chris/media/Music; and ls -a"
abbr mn "cd /mnt; and ls -a"
abbr pp "cd /home/chris/pixs; and ls -a"
abbr sc "cd /home/chris/.local/bin; and ls -a"
abbr vv "cd /home/chris/media/Videos; and ls -a"
abbr bf "$EDITOR /home/chris/.config//shell/bm-files" 
abbr bd "$EDITOR /home/chris/.config//shell/bm-dirs" 
abbr cfv "$EDITOR /home/chris/.config//nvim/init.lua" 
abbr cfz "$EDITOR /home/chris/.config/zsh/.zshrc" 
abbr cfa "$EDITOR /home/chris/.config//shell/aliasrc" 
abbr cff "$EDITOR /home/chris/.config//fish/config.fish" 
abbr cfm "$EDITOR /home/chris/.config//mutt/muttrc" 
abbr cfn "$EDITOR /home/chris/.config//newsboat/config" 
abbr cfu "$EDITOR /home/chris/.config//newsboat/urls" 
abbr cfmb "$EDITOR /home/chris/.config//ncmpcpp/bindings" 
abbr cfmc "$EDITOR /home/chris/.config//ncmpcpp/config" 
abbr cfl "$EDITOR /home/chris/.config//lf/lfrc" 
abbr cfL "$EDITOR /home/chris/.config//lf/scope" 
abbr cfX "$EDITOR /home/chris/.config//sxiv/exec/key-handler" 
abbr cfd "$EDITOR /home/chris/.config//suckless/dwm/config.h" 
