# vim: filetype=sh
abbr cac "cd /home/chris/.cache/; and ls -a"
abbr cf "cd /home/chris/.config/; and ls -a"
abbr D "cd /home/chris/dl; and ls -a"
abbr d "cd /home/chris/docs; and ls -a"
abbr rs "cd /home/chris/.local/share; and ls -a"
abbr dt "cd /home/chris/docs/tex/; and ls -a"
abbr ds "cd /home/chris/docs/ms/; and ls -a"
abbr dp "cd /home/chris/docs/props/; and ls -a"
abbr dr "cd /home/chris/docs/rmd/; and ls -a"
abbr dri "cd /home/chris/docs/rmd/it-projects/; and ls -a"
abbr dm "cd /home/chris/docs/md/; and ls -a"
abbr rr "cd /home/chris/.local/.src; and ls -a"
abbr M "cd /home/chris/media; and ls -a"
abbr ce "cd /home/chris/copywriting/english-rules/; and ls -a"
abbr cw "cd /home/chris/copywriting/copying-writers/; and ls -a"
abbr sw "cd /home/chris/copywriting/swipes/; and ls -a"
abbr swh "cd /home/chris/copywriting/swipes/headlines/; and ls -a"
abbr h "cd /home/chris; and ls -a"
abbr mn "cd /mnt; and ls -a"
abbr pp "cd /home/chris/pixs; and ls -a"
abbr sc "cd /home/chris/.local/bin; and ls -a"
abbr vv "cd /zpgen/shared/vids/; and ls -a"
abbr bf "$EDITOR /home/chris/.config//shell/bm-files" 
abbr bd "$EDITOR /home/chris/.config//shell/bm-dirs" 
abbr cfv "$EDITOR /home/chris/.config//nvim/init.lua" 
abbr cft "$EDITOR /home/chris/.config//tmux/tmux.conf" 
abbr cfz "$EDITOR /home/chris/.config/zsh/.zshrc" 
abbr cfa "$EDITOR /home/chris/.config//shell/aliasrc" 
abbr cff "$EDITOR /home/chris/.config//fish/config.fish" 
abbr cfm "$EDITOR /home/chris/.config//mutt/muttrc" 
abbr cfn "$EDITOR /home/chris/.config//newsboat/config" 
abbr cfu "$EDITOR /home/chris/.config//newsboat/urls" 
abbr cfmb "$EDITOR /home/chris/.config//ncmpcpp/bindings" 
abbr cfmc "$EDITOR /home/chris/.config//ncmpcpp/config" 
abbr cfl "$EDITOR /home/chris/.config//lf/lfrc" 
abbr cfL "$EDITOR /home/chris/.config//lf/scope" 
abbr cfX "$EDITOR /home/chris/.config//sxiv/exec/key-handler" 
abbr cfd "$EDITOR /home/chris/.config//suckless/dwm/config.h" 
