# vim: filetype=sh
abbr cac "cd ~/.cache; and ls -a"
abbr cf "cd ~/.config; and ls -a"
abbr D "cd ~/dl; and ls -a"
abbr d "cd ~/docs; and ls -a"
abbr rs "cd ~/.local/share; and ls -a"
abbr dp "cd ~/docs/props/; and ls -a"
abbr dm "cd ~/docs/md/; and ls -a"
abbr rr "cd ~/.local/.src; and ls -a"
abbr M "cd ~/media; and ls -a"
abbr ce "cd ~/copywriting/english-rules/; and ls -a"
abbr sw "cd ~/copywriting/swipes/; and ls -a"
abbr swh "cd ~/copywriting/swipes/headlines/; and ls -a"
abbr h "cd ~/; and ls -a"
abbr mn "cd /mnt; and ls -a"
abbr pp "cd ~/pix; and ls -a"
abbr sc "cd ~/.local/bin; and ls -a"
abbr vv "cd /zpgen/shared/vids/; and ls -a"
abbr bf "$EDITOR /home/chris/.config//shell/bm-files" 
abbr bd "$EDITOR /home/chris/.config//shell/bm-dirs" 
abbr cfv "$EDITOR /home/chris/.config//nvim/init.lua" 
abbr cft "$EDITOR /home/chris/.config//tmux/tmux.conf" 
abbr cfz "$EDITOR /home/chris/.config/zsh/.zshrc" 
abbr cfa "$EDITOR /home/chris/.config//shell/aliasrc" 
abbr cff "$EDITOR /home/chris/.config//fish/config.fish" 
abbr cfm "$EDITOR /home/chris/.config//mutt/muttrc" 
abbr cfn "$EDITOR /home/chris/.config//newsboat/config" 
abbr cfu "$EDITOR /home/chris/.config//newsboat/urls" 
abbr cfmb "$EDITOR /home/chris/.config//ncmpcpp/bindings" 
abbr cfmc "$EDITOR /home/chris/.config//ncmpcpp/config" 
abbr cfl "$EDITOR /home/chris/.config//lf/lfrc" 
abbr cfL "$EDITOR /home/chris/.config//lf/scope" 
abbr cfX "$EDITOR /home/chris/.config//sxiv/exec/key-handler" 
abbr cfd "$EDITOR /home/chris/.config//suckless/dwm/config.h" 
