#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json
blacklist = ["popup"]

sort_order = [
    "tmux",
    "tmuxinator", # show first
    "config",
    "zoxide", # show last
]

[tui]
prompt = "> "
placeholder = "Filter sessions... "
show_icons = true
show_windows = true
alias_auto_connect_delay = "150ms"
alias_filter_prefix = "/"
preview = false
preview_width = 60
preview_min_width = 100
preview_border = "line"

# [[session]]
# name = "sesh"
# path = "~/c/sesh"
# icon = ""
