-- Swayimg configuration (converted from INI format)
-- Place at: $HOME/.config/swayimg/init.lua

--------------------------------------------------------------------------------
-- General
--------------------------------------------------------------------------------
swayimg.set_mode("viewer")
swayimg.enable_antialiasing(true)
swayimg.enable_decoration(false)
swayimg.enable_overlay(false)
swayimg.enable_exif_orientation(true)

--------------------------------------------------------------------------------
-- Image list
--------------------------------------------------------------------------------
swayimg.imagelist.set_order("alpha")
swayimg.imagelist.enable_reverse(false)
swayimg.imagelist.enable_recursive(false)
swayimg.imagelist.enable_adjacent(false)
swayimg.imagelist.enable_fsmon(true)

--------------------------------------------------------------------------------
-- Font / text overlay
--------------------------------------------------------------------------------
swayimg.text.set_font("monospace")
swayimg.text.set_size(8)
swayimg.text.set_padding(10)
swayimg.text.set_foreground(0xffcad3f5)
swayimg.text.set_shadow(0xd0181926)
swayimg.text.set_background(0x00181926)
swayimg.text.set_timeout(0)
swayimg.text.set_status_timeout(3)

--------------------------------------------------------------------------------
-- Viewer mode
--------------------------------------------------------------------------------
swayimg.viewer.set_default_scale("optimal")
swayimg.viewer.set_default_position("center")
swayimg.viewer.set_drag_button("MouseLeft")
swayimg.viewer.set_window_background(0x00181926)
swayimg.viewer.set_image_chessboard(20, 0xff333333, 0xff4c4c4c)
swayimg.viewer.enable_centering(true)
swayimg.viewer.enable_loop(true)
swayimg.viewer.limit_preload(1)
swayimg.viewer.limit_history(1)

swayimg.viewer.set_text("topleft", {})
swayimg.viewer.set_text("topright", {})
swayimg.viewer.set_text("bottomleft", { "{list.index} of {list.total}", "{scale}", "{frame.index} of {frame.total}" })
swayimg.viewer.set_text("bottomright", { "{name}", "{status}" })

--------------------------------------------------------------------------------
-- Viewer keybindings
--------------------------------------------------------------------------------

-- Navigation
swayimg.viewer.on_key("p", function()
	swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_key("n", function()
	swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_key("Space", function()
	swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_key("Shift+r", function()
	swayimg.viewer.switch_image("random")
end)
swayimg.viewer.on_key("Shift+d", function()
	swayimg.viewer.switch_image("prev_dir")
end)
swayimg.viewer.on_key("d", function()
	swayimg.viewer.switch_image("next_dir")
end)
swayimg.viewer.on_key("g", function()
	swayimg.viewer.switch_image("first")
end)
swayimg.viewer.on_key("Shift+g", function()
	swayimg.viewer.switch_image("last")
end)

-- Frames
swayimg.viewer.on_key("Shift+o", function()
	swayimg.viewer.prev_frame()
end)
swayimg.viewer.on_key("o", function()
	swayimg.viewer.next_frame()
end)

-- Mode switches
swayimg.viewer.on_key("s", function()
	swayimg.set_mode("slideshow")
end)
swayimg.viewer.on_key("Return", function()
	swayimg.set_mode("gallery")
end)

-- Fullscreen / misc
swayimg.viewer.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
swayimg.viewer.on_key("r", function()
	swayimg.viewer.reload()
end)
swayimg.viewer.on_key("c", function()
	swayimg.imagelist.remove(swayimg.viewer.get_image().path)
end)

-- Pan (1/10 of window per keypress, matching the INI `step_left/right/up/down 10`)
swayimg.viewer.on_key("h", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(math.floor(pos.x + wnd.width / 10), pos.y)
end)
swayimg.viewer.on_key("l", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(math.floor(pos.x - wnd.width / 10), pos.y)
end)
swayimg.viewer.on_key("k", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x, math.floor(pos.y + wnd.height / 10))
end)
swayimg.viewer.on_key("j", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x, math.floor(pos.y - wnd.height / 10))
end)

-- Zoom (+/- 10% of current scale)
swayimg.viewer.on_key("Equal", function()
	local s = swayimg.viewer.get_scale()
	swayimg.viewer.set_abs_scale(s + s * 0.1)
end)
swayimg.viewer.on_key("Plus", function()
	local s = swayimg.viewer.get_scale()
	swayimg.viewer.set_abs_scale(s + s * 0.1)
end)
swayimg.viewer.on_key("Minus", function()
	local s = swayimg.viewer.get_scale()
	swayimg.viewer.set_abs_scale(s - s * 0.1)
end)
swayimg.viewer.on_key("w", function()
	swayimg.viewer.set_fix_scale("width")
end)
swayimg.viewer.on_key("Shift+w", function()
	swayimg.viewer.set_fix_scale("height")
end)
swayimg.viewer.on_key("z", function()
	swayimg.viewer.set_fix_scale("fit")
end)
swayimg.viewer.on_key("Shift+z", function()
	swayimg.viewer.set_fix_scale("fill")
end)
swayimg.viewer.on_key("0", function()
	swayimg.viewer.set_fix_scale("real")
end)
swayimg.viewer.on_key("BackSpace", function()
	swayimg.viewer.set_fix_scale("optimal")
end)
swayimg.viewer.on_key("i", function()
	swayimg.viewer.set_fix_scale("keep")
end)

-- Transform
swayimg.viewer.on_key("bracketright", function()
	swayimg.viewer.rotate(90)
end)
swayimg.viewer.on_key("bracketleft", function()
	swayimg.viewer.rotate(270)
end)
swayimg.viewer.on_key("m", function()
	swayimg.viewer.flip_vertical()
end)
swayimg.viewer.on_key("Shift+m", function()
	swayimg.viewer.flip_horizontal()
end)

-- Exit
swayimg.viewer.on_key("Escape", function()
	swayimg.exit()
end)
swayimg.viewer.on_key("q", function()
	swayimg.exit()
end)

-- Custom exec bindings
swayimg.viewer.on_key("Ctrl+w", function()
	local image = swayimg.viewer.get_image()
	os.execute("/home/chris/.local/bin/setbg '" .. image.path .. "'")
end)
swayimg.viewer.on_key("Ctrl+r", function()
	local image = swayimg.viewer.get_image()
	os.execute("magick '" .. image.path .. "' -rotate 90 '" .. image.path .. "'")
end)
swayimg.viewer.on_key("Ctrl+c", function()
	local image = swayimg.viewer.get_image()
	os.execute("echo -n '" .. image.path .. "' | wl-copy")
end)
swayimg.viewer.on_key("Ctrl+g", function()
	local image = swayimg.viewer.get_image()
	os.execute("gimp '" .. image.path .. "'")
end)
-- Delete file (overrides Shift+d nav binding above, same as INI where last binding wins)
swayimg.viewer.on_key("Shift+d", function()
	local image = swayimg.viewer.get_image()
	os.execute("rm -f '" .. image.path .. "' && notify-send '❌ File removed: " .. image.path .. "'")
	swayimg.imagelist.remove(image.path)
end)

-- Mouse bindings
swayimg.viewer.on_mouse("ScrollLeft", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(math.floor(pos.x - wnd.width / 20), pos.y)
end)
swayimg.viewer.on_mouse("ScrollRight", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(math.floor(pos.x + wnd.width / 20), pos.y)
end)
swayimg.viewer.on_mouse("ScrollUp", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x, math.floor(pos.y + wnd.height / 20))
end)
swayimg.viewer.on_mouse("ScrollDown", function()
	local wnd = swayimg.get_window_size()
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x, math.floor(pos.y - wnd.height / 20))
end)
swayimg.viewer.on_mouse("Ctrl+ScrollUp", function()
	local pos = swayimg.get_mouse_pos()
	local s = swayimg.viewer.get_scale()
	swayimg.viewer.set_abs_scale(s + s / 10, pos.x, pos.y)
end)
swayimg.viewer.on_mouse("Ctrl+ScrollDown", function()
	local pos = swayimg.get_mouse_pos()
	local s = swayimg.viewer.get_scale()
	swayimg.viewer.set_abs_scale(s - s / 10, pos.x, pos.y)
end)
swayimg.viewer.on_mouse("Shift+ScrollUp", function()
	swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_mouse("Shift+ScrollDown", function()
	swayimg.viewer.switch_image("next")
end)
swayimg.viewer.on_mouse("Alt+ScrollUp", function()
	swayimg.viewer.prev_frame()
end)
swayimg.viewer.on_mouse("Alt+ScrollDown", function()
	swayimg.viewer.next_frame()
end)
swayimg.viewer.on_mouse("MouseSide", function()
	swayimg.viewer.switch_image("prev")
end)
swayimg.viewer.on_mouse("MouseExtra", function()
	swayimg.viewer.switch_image("next")
end)

--------------------------------------------------------------------------------
-- Slideshow mode (inherits viewer, so switch_image works the same way)
--------------------------------------------------------------------------------
swayimg.slideshow.set_timeout(3)
swayimg.slideshow.set_default_scale("fit")
swayimg.slideshow.set_window_background("auto")
swayimg.slideshow.limit_history(0)

swayimg.slideshow.set_text("topleft", {})
swayimg.slideshow.set_text("topright", {})
swayimg.slideshow.set_text("bottomleft", {})
swayimg.slideshow.set_text("bottomright", { "{dir}", "{status}" })

swayimg.slideshow.on_key("g", function()
	swayimg.slideshow.switch_image("first")
end)
swayimg.slideshow.on_key("Shift+g", function()
	swayimg.slideshow.switch_image("last")
end)
swayimg.slideshow.on_key("h", function()
	swayimg.slideshow.switch_image("prev")
end)
swayimg.slideshow.on_key("l", function()
	swayimg.slideshow.switch_image("next")
end)
swayimg.slideshow.on_key("Shift+r", function()
	swayimg.slideshow.switch_image("random")
end)
swayimg.slideshow.on_key("Shift+d", function()
	swayimg.slideshow.switch_image("prev_dir")
end)
swayimg.slideshow.on_key("d", function()
	swayimg.slideshow.switch_image("next_dir")
end)
swayimg.slideshow.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
swayimg.slideshow.on_key("Return", function()
	swayimg.set_mode("viewer")
end)
swayimg.slideshow.on_key("Escape", function()
	swayimg.exit()
end)
swayimg.slideshow.on_key("q", function()
	swayimg.exit()
end)

--------------------------------------------------------------------------------
-- Gallery mode
--------------------------------------------------------------------------------
swayimg.gallery.set_aspect("fill")
swayimg.gallery.set_thumb_size(150)
swayimg.gallery.set_padding_size(10)
swayimg.gallery.set_border_size(5)
swayimg.gallery.set_border_color(0xffee99a0)
swayimg.gallery.set_selected_scale(1.15)
swayimg.gallery.set_selected_color(0xff24273a)
swayimg.gallery.set_unselected_color(0xff24273a)
swayimg.gallery.set_window_color(0xff181926)
swayimg.gallery.limit_cache(100)
swayimg.gallery.enable_preload(false)
swayimg.gallery.enable_pstore(false)

swayimg.gallery.set_text("topleft", {})
swayimg.gallery.set_text("topright", {})
swayimg.gallery.set_text("bottomleft", { "{list.index} of {list.total}" })
swayimg.gallery.set_text("bottomright", { "{name}", "{status}" })

swayimg.gallery.on_key("g", function()
	swayimg.gallery.switch_image("first")
end)
swayimg.gallery.on_key("Shift+g", function()
	swayimg.gallery.switch_image("last")
end)
swayimg.gallery.on_key("h", function()
	swayimg.gallery.switch_image("left")
end)
swayimg.gallery.on_key("l", function()
	swayimg.gallery.switch_image("right")
end)
swayimg.gallery.on_key("k", function()
	swayimg.gallery.switch_image("up")
end)
swayimg.gallery.on_key("j", function()
	swayimg.gallery.switch_image("down")
end)
swayimg.gallery.on_key("Ctrl+u", function()
	swayimg.gallery.switch_image("pgup")
end)
swayimg.gallery.on_key("Ctrl+d", function()
	swayimg.gallery.switch_image("pgdown")
end)
swayimg.gallery.on_key("s", function()
	swayimg.set_mode("slideshow")
end)
swayimg.gallery.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
swayimg.gallery.on_key("Return", function()
	swayimg.set_mode("viewer")
end)
swayimg.gallery.on_key("r", function()
	local sz = swayimg.gallery.get_thumb_size()
	swayimg.gallery.set_thumb_size(sz) -- reload equivalent: reset size to trigger redraw
end)
swayimg.gallery.on_key("Equal", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() + 20)
end)
swayimg.gallery.on_key("Plus", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() + 20)
end)
swayimg.gallery.on_key("Minus", function()
	swayimg.gallery.set_thumb_size(math.max(20, swayimg.gallery.get_thumb_size() - 20))
end)
swayimg.gallery.on_key("Escape", function()
	swayimg.exit()
end)
swayimg.gallery.on_key("q", function()
	swayimg.exit()
end)

-- Gallery custom exec bindings
swayimg.gallery.on_key("Ctrl+w", function()
	local image = swayimg.gallery.get_image()
	os.execute("/home/chris/.local/bin/setbg '" .. image.path .. "'")
end)
swayimg.gallery.on_key("Ctrl+r", function()
	local image = swayimg.gallery.get_image()
	os.execute("magick '" .. image.path .. "' -rotate 90 '" .. image.path .. "'")
end)
swayimg.gallery.on_key("Ctrl+c", function()
	local image = swayimg.gallery.get_image()
	os.execute("echo -n '" .. image.path .. "' | wl-copy")
end)
swayimg.gallery.on_key("Shift+d", function()
	local image = swayimg.gallery.get_image()
	os.execute("rm -f '" .. image.path .. "' && notify-send '❌ File removed: " .. image.path .. "'")
	swayimg.imagelist.remove(image.path)
end)
swayimg.gallery.on_key("Ctrl+g", function()
	local image = swayimg.gallery.get_image()
	os.execute("gimp '" .. image.path .. "'")
end)

-- Gallery mouse bindings
swayimg.gallery.on_mouse("ScrollLeft", function()
	swayimg.gallery.switch_image("right")
end)
swayimg.gallery.on_mouse("ScrollRight", function()
	swayimg.gallery.switch_image("left")
end)
swayimg.gallery.on_mouse("ScrollUp", function()
	swayimg.gallery.switch_image("up")
end)
swayimg.gallery.on_mouse("ScrollDown", function()
	swayimg.gallery.switch_image("down")
end)
swayimg.gallery.on_mouse("Ctrl+ScrollUp", function()
	swayimg.gallery.set_thumb_size(swayimg.gallery.get_thumb_size() + 20)
end)
swayimg.gallery.on_mouse("Ctrl+ScrollDown", function()
	swayimg.gallery.set_thumb_size(math.max(20, swayimg.gallery.get_thumb_size() - 20))
end)
swayimg.gallery.on_mouse("MouseLeft", function()
	swayimg.set_mode("viewer")
end)

--------------------------------------------------------------------------------
-- Window resize: force scale for tiling compositors
--------------------------------------------------------------------------------
swayimg.on_window_resize(function()
	swayimg.viewer.set_fix_scale("optimal")
end)
