reload "user.plugins"
reload "user.tokyonight"
-- reload "user.catppuccin"
-- reload "user.onedarkpro"
-- reload "user.rose-pine"
-- reload "user.doomone"
-- reload "user.kanagawa"
reload "user.colorscheme"
reload "user.autocommands"
reload "user.telescope"
reload "user.keymaps"
reload "user.cybu"
reload "user.noice"
reload "user.whichkey"
reload "user.options"
reload "user.builtins"
reload "user.lsp"
reload "user.abbreviations"
reload "user.colorizer"
-- reload "user.hop"
reload "user.bqf"
reload "user.numb"
reload "user.jaq"
-- reload "user.surround"
-- reload "user.treesitter"
reload "user.quickscope"
reload "user.true-zen"
reload "user.lsp-inlayhints"
reload "user.twilight"
reload "user.zen-mode"
reload "user.neoscroll"
reload "user.auto-session"
reload "user.harpoon"
reload "user.zk"
-- reload "user.lualine"

