# abook
# Autogenerated from man page /usr/share/man/man1/abook.1.gz
complete -c abook -s h -l help -d 'Show usage'
complete -c abook -s C -l config -d 'Use an alternative configuration file (default is $HOME/'
complete -c abook -l datafile -d 'Use an alternative addressbook file (default is $HOME/'
complete -c abook -l mutt-query -l outformat -d 'Make a query for mutt (search the addressbook for <string>)'
complete -c abook -l convert -l informat -l infile -l outfile -d 'Converts <inputfile> in <inputformat> to <outputfile> in <outputformat> (defa…'
complete -c abook -l outformatstr -d 'Only used if --mutt-query or --convert is specified and --outformat=custom'
complete -c abook -l add-email -d 'Read an e-mail message from stdin and add the sender to the addressbook'
complete -c abook -l add-email-quiet -d 'Same as --add-email but doesn\'t confirm adding'
complete -c abook -l formats -d 'List available formats'

