# entr
# Autogenerated from man page /usr/share/man/man1/entr.1.gz
complete -c entr -s a -d 'Respond to all events which occur while the utility is running'
complete -c entr -s c -d 'Clear the screen before invoking the utility specified on the command line'
complete -c entr -s d -d 'Track the directories of regular files provided as input and exit if a new fi…'
complete -c entr -s n -d 'Run in non-interactive mode'
complete -c entr -s p -d 'Postpone the first execution of the utility until a file is modified'
complete -c entr -s r -d 'Reload a persistent child process'
complete -c entr -s s -d 'Evaluate the first argument using the interpreter specified by the SHELL envi…'
complete -c entr -s z -d 'Exit after the utility completes'

