# gnucash-cli
# Autogenerated from man page /usr/share/man/man1/gnucash-cli.1.gz
complete -c gnucash-cli -l namespace -d 'Regular expression determining which namespace commodities will be retrieved'
complete -c gnucash-cli -l name -d 'Name of the report to run'
complete -c gnucash-cli -l export-type -d 'Specify export type General Options'
complete -c gnucash-cli -l version -d 'Show GnuCash version'
complete -c gnucash-cli -l help -d 'Show this help message'
complete -c gnucash-cli -l debug -d 'Enable debugging mode: increasing logging to provide deep detail'
complete -c gnucash-cli -l extra -d 'Enable extra/development/debugging features'
complete -c gnucash-cli -l log -d 'Log level overrides, of the form "log. ger'
complete -c gnucash-cli -l logto -d 'File to log into; defaults to "/tmp/gnucash'

