# gnucash
# Autogenerated from man page /usr/share/man/man1/gnucash.1.gz
complete -c gnucash -l version -d 'Show  GnuCash version'
complete -c gnucash -l help -d 'Show this help message'
complete -c gnucash -l debug -d 'Enable debugging mode: increasing logging to provide deep detail'
complete -c gnucash -l extra -d 'Enable extra/development/debugging features'
complete -c gnucash -l log -d 'Log level overrides, of the form "log. ger'
complete -c gnucash -l logto -d 'File to log into; defaults to "/tmp/gnucash'
complete -c gnucash -l nofile -d 'Do not load the last file opened'
complete -c gnucash -l add-price-quotes -d 'Add price quotes to the given data file'
complete -c gnucash -l namespace -d 'Regular expression determining which namespace commodities will be retrieved'

