# ktoblzcheck
# Autogenerated from man page /usr/share/man/man1/ktoblzcheck.1.gz
complete -c ktoblzcheck -l returncode -d 'If given, the result is returned via the returncode and no output on the term…'
complete -c ktoblzcheck -l file -d 'Specifies the file with the bankdata'

