# mbsync
# Autogenerated from man page /usr/share/man/man1/mbsync.1.gz
complete -c mbsync -s c -l config -d 'Read configuration from file.  By default, the configuration is read from ~/'
complete -c mbsync -s a -l all -d 'Select all configured channels'
complete -c mbsync -s l -l list -d 'Don\'t synchronize anything, but list all mailboxes in the selected channels a…'
complete -c mbsync -s C -l 'create[-far' -o near -d 'Override any Create options from the config file.  See below'
complete -c mbsync -s R -l 'remove[-far' -d 'Override any Remove options from the config file.  See below'
complete -c mbsync -s X -l 'expunge[-far' -d 'Override any Expunge options from the config file.  See below'
complete -c mbsync -s n -s N -s d -s f -s 0 -s F -d '{--new|--renew|--delete|--flags|--noop|--full}'
complete -c mbsync -s H -d '{--pull|--push}[-new|-renew|-delete|-flags] Override any Sync options from th…'
complete -c mbsync -s h -l help -d 'Display a summary of command line options'
complete -c mbsync -s v -l version -d 'Display version information'
complete -c mbsync -s V -l verbose -d 'Enable verbose mode, which displays what is currently happening'
complete -c mbsync -o 'D[d' -d '--debug[-crash|-driver|-driver-all|-maildir|-main|-net|-net-all|-sync] Enable…'
complete -c mbsync -s q -l quiet -d 'Suppress progress counters (this is implicit if stdout is no TTY, or any debu…'
complete -c mbsync -s w -d 'password ['
complete -c mbsync -s T -d '/path/to/mbsync ] Tunnel command Specify a command to run to establish a conn…'

