# mpopd
# Autogenerated from man page /usr/share/man/man1/mpopd.1.gz
complete -c mpopd -l version -d 'Print version information'
complete -c mpopd -l help -d 'Print help'
complete -c mpopd -l inetd -d 'Start single POP3 session on stdin/stdout'
complete -c mpopd -l interface -d 'Listen on the given IPv6 or IPv4 address instead of 127. 0. 0. 1'
complete -c mpopd -l port -d 'Listen on the given port number instead of 25'
complete -c mpopd -l log -d 'Set logging: none (default), syslog, or logging to the given file'
complete -c mpopd -l auth -d 'Require authentication with this user name'
complete -c mpopd -l maildir -d 'Use this maildir as the mailbox.  EXAMPLES'

