# sc-im
# Autogenerated from man page /usr/share/man/man1/sc-im.1.gz
complete -c sc-im -l sheet -d 'Open SHEET when loading xlsx file.  Can be sheet name or number'
complete -c sc-im -l version -d 'Print the version number of Sc-im and exit'
complete -c sc-im -l nocurses -d 'Run interactive but without ncurses interface'
complete -c sc-im -l output -d 'Save the results in FILE'
complete -c sc-im -l quit_afterload -d 'Quit after loading all the files.  Useful when sending scripts to SC-IM'
complete -c sc-im -l quiet -d 'Set variable \'quiet\'.  Avoid printing info/error/debug messages'
complete -c sc-im -l autocalc -d 'Set variable \'autocalc\'.  Recalculations occur automatically'
complete -c sc-im -l numeric -d 'Set variable \'numeric\''
complete -c sc-im -l half_page_scroll -d 'Set variable \'half_page_scroll\''
complete -c sc-im -l newline_action -d 'Set variable \'newline_action\' VAL to R j to move the cursor down after an ent…'
complete -c sc-im -l external_functions -d 'Set variable \'external_functions\'.  Enable external functions'
complete -c sc-im -l xlsx_readformulas -d 'Set variable \'xlsx_readformulas\''

