# sdcv
# Autogenerated from man page /usr/share/man/man1/sdcv.1.gz
complete -c sdcv -s h -l help -d 'Display help message and exit'
complete -c sdcv -s v -l version -d 'Display version and exit'
complete -c sdcv -s l -l list-dicts -d 'Display list of available dictionaries and exit'
complete -c sdcv -s u -l use-dict -d 'For search use only dictionary with this bookname'
complete -c sdcv -s n -l non-interactive -d 'For use in scripts'
complete -c sdcv -s x -l only-data-dir -d 'For use in scripts: only use the dictionaries in data-dir, do not search in u…'
complete -c sdcv -s e -l exact-search -d 'Do not fuzzy-search for similar words, only return exact matches'
complete -c sdcv -s j -l json -d 'Print the results of list-dicts and searches as json, not as plain text'
complete -c sdcv -l utf8-output -d 'Force sdcv to not convert to locale charset, output in utf8'
complete -c sdcv -l utf8-input -d 'Force sdcv to not convert from locale charset, assume that input is in utf8'
complete -c sdcv -l data-dir -d 'Use this directory as the path to the stardict data directory'
complete -c sdcv -l color -d 'Use ANSI escape codes for colorizing sdcv output (does not work with json out…'

