# slstatus
# Autogenerated from man page /usr/local/man/man1/slstatus.1
complete -c slstatus -s s -d 'Write to stdout instead of WM_NAME'
complete -c slstatus -s 1 -d 'Write once to stdout and quit'

