# xkeycaps
# Autogenerated from man page /usr/share/man/man1/xkeycaps.1x.gz
complete -c xkeycaps -o keyboard -o kbd -d 'Specifies the type of keyboard to display'
complete -c xkeycaps -o help -d 'Lists the recognized values for the -keyboard option'
complete -c xkeycaps -o gutterwidth -o gw -d 'Specifies the number of pixels of space to leave between each key'
complete -c xkeycaps -o font -d 'Specifies the font to use to display the keycaps'
complete -c xkeycaps -o display -d 'This option specifies the X server to contact'
complete -c xkeycaps -o geometry -d 'This option specifies the preferred size and position of the window'
complete -c xkeycaps -o bg -d 'This option specifies the color to use for the background of the window'
complete -c xkeycaps -o fg -d 'This option specifies the color to use for the foreground of the window'
complete -c xkeycaps -o bw -d 'This option specifies the width in pixels of the border surrounding  the wind…'
complete -c xkeycaps -o xrm -d 'This option specifies a resource string to be used'

