abbr em "doas emerge --ask"
abbr ew "doas emerge-webrsync"
abbr ea "doas emaint -a sync"
abbr ems "doas emerge --sync"
abbr emn "doas emerge --ask --update --deep --newuse --keep-going @world"
abbr emc "doas emerge --ask --update --deep --changed-use --keep-going @world"
abbr ema "doas emerge --ask --autounmask"
abbr emu "doas emerge --ask -uDU --keep-going --with-bdeps=y @world"
abbr emd "doas emerge --ask --depclean"
abbr emds "doas emerge --ask --deselect"
abbr update-grub "doas grub-mkconfig -o /boot/grub/grub.cfg"
abbr ke "cd /usr/src/linux/ && doas make menuconfig"
abbr drivers "doas emerge @module-rebuild"
abbr golang "doas emerge @golang-rebuild"
# abbr mk "doas /usr/src/linux/rebuild-kernel.sh"
